### ISSUE TITLE
Unit Tests and CI

### ISSUE THREAD

**Issue by ghost** [MrMoose/CloudConnector#1]
Hey guys,

can we add some form of unit tests and CI (via github actions) to this wonderful project? :)
Thx in advance!

**Comment by MrMoose** [comment]
Yes, agreed, that would be terrific. I am currently investigating if there is anything within the Unreal Engine which would allow for automated functional testing of this but so far I haven't found anything suitable.
I will try to find an answer for a bit but to be honest I wouldn't hold my breath.

I am currently working on a overarching demo project which integrates this and another plugin for rendering which will at least serve as an integration test platform by using this. This is not ready yet.

**Comment by MrMoose** [comment]
OP is ghosted. I'm closing this
