### ISSUE TITLE
Exactly-once delivery support for GoogleCloud pubsub

### ISSUE THREAD

**Issue by Shevchenko-Alexander** [MrMoose/CloudConnector#4]
Google Cloud Pub/Sub does not guarantee that we will not get duplicated messages since it offers at-least-once delivery semantics.
In some cases it leads to issues if we are receaving these duplicates if we don't have any client implementation to handle such cases. In distributed solutions with more then one client it even not possible to handle that. It would be great to have a possibility of "Exactly-once delivery" in the CloudConnector:
[https://stackoverflow.com/questions/72074775/why-does-gcp-pub-sub-publish-a-message-twice](https://stackoverflow.com/questions/72074775/why-does-gcp-pub-sub-publish-a-message-twice)

Not sure if the "ExactlyOnceAckHandler" class could be used, instead of "AckHandler":
[https://googleapis.dev/cpp/google-cloud-pubsub/latest/classgoogle_1_1cloud_1_1pubsub_1_1ExactlyOnceAckHandler.html](https://googleapis.dev/cpp/google-cloud-pubsub/latest/classgoogle_1_1cloud_1_1pubsub_1_1ExactlyOnceAckHandler.html)

**Comment by MrMoose** [comment]
The way CloudConnector re-uses an existing subscription which potentially may already have exactly-once-delivery enabled may very well overwrite settings since the upgrade of the SDK to 2.3.0.

This needs to be addressed.

**Comment by MrMoose** [comment]
I consider this fixed with v1.1.0
