### ISSUE TITLE
Build Instructions for opentelemetry-cpp

### ISSUE THREAD

**Issue by cnbleu** [MrMoose/CloudConnector#6]
Hi @MrMoose ,

I wonder if I could ask you how to build opentelemetry-cpp for Unreal Engine 4/5 on Windows 10 platform. Can you share your build scripts to me?  I have tried many times but still failed (build success but run failed). I'm building the otel-cpp project with `setup-buildtools.cmd` and `build.cmd`  scripts where under the opentelemetry-cpp/tools source code directory.

**Comment by MrMoose** [comment]
Hello @cnbleu,

build scripts are included in here. You can find instructions in the README.md docs. The script is under Scripts/build_deps.py
It will build all the dependencies including OpenTelemetry

HTH,
Moose

**Comment by cnbleu** [comment]
@MrMoose Thank you! I have build with the `build_deps.py` on my Windows 10. Building were very positive until an error occurs when building grpc:
```
libprotobuf-lite.lib(libprotobuf-lite.dll) : error LNK2005: "public: __cdecl google::protobuf::io::CodedOutputStream::~CodedOutputStream(void)" (??1CodedOutputStream@io@protobu
f@google@@QEAA@XZ) already defined in libprotobuf.lib(coded_stream.obj [C:\source\CloudConnector\Scripts\raw\grpc-1.49.2\_build\grpc_cpp_plugin.vcxproj]
```
I don't known the reason for this failure. I didn't change any configuration information from `build_deps.py` and any other files. Can you help me? Thanks!

**Comment by MrMoose** [comment]
I wanted to update anyway, let me see what I can do.
In the meantime, please verify that you have all the correct dependencies for the status quo. Namely VS2019. Just in case.

**Comment by cnbleu** [comment]
Thank you, Moose. Follow is my dependencies:

1. VS2019: Microsoft Visual Studio Community 2019 (Version Number: 16.11.25)
2. Windows SDK:  Windows SDK version 10.0.19041.0
3. C compiler: MSVC 19.29.30148.0 (ABI: x64)
4. CXX compiler: MSVC 19.29.30148.0 (ABI: x64)
5. Python
```
> python --version
> Python 3.11.2
```
6. Perl
```
> perl --version
> This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread
```
7. CMake
```
> cmake --version
> cmake version 3.25.3
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
8. nmake
```
> nmake/?
> 14.29.30148.0
```

The `build_deps.py` is also running in the `x64 Native Tools Command Prompt` shell.

Above dependencies are already configured in system path:
<img src="https://user-images.githubusercontent.com/3634065/231912286-e7654026-b6c0-4f2a-be58-69cfce01bfdc.png" width="300">

According to the [256-character-filenames](https://github.com/MrMoose/CloudConnector/blob/master/Scripts/README.md#256-character-filenames), I have already move the source code to `C:\source\CloudConnector` dir.


One more thing:
When creating CMake build files, there was a warnning:
```
CMake Warning:
Manually-specified variables were not used by the project:

   BUILD_TESTING
   PROTOBUF_USE_DLLS
```
I'm not sure above warnings made a difference.

Thank you Moose, please let me know if you need more information.

**Comment by MrMoose** [comment]
Thanks, this all looks very much all right.
I can't see what would be causing this but the build process, as you can see is very complex and quite error prone.
I'm currently in the process of bumping all the dependencies to more recent versions, VS2022 and Unreal Engine 5.x. 
This may fix your problem. I'm doing some tests with the new versions right now and keep you informed.

**Comment by cnbleu** [comment]
Ok, you are doing a great job! I'll build with the scripts again in a new system, and will try your version when it's ready. Thanks.

**Comment by MrMoose** [comment]
Thanks, I have updated the scripts to recent versions in master. I wanted to prepare for UE5 anyway. So if you could pull current master and try the scripts with that?

Note that I have only been able to develop and test this using Visual Studio 2022 which is not entirely binary compatible with UE5 unless I install an older (VS2019) toolchain along with and specify it in the CMake targets.

Since you said you are using VS2019 this shouldn't be necessary for you. If the scripts complain about wrong compiler versions right in the beginning, go to line 49 and replace
cmake_toolset = "-T v142,version=14.29"
with
cmake_toolset = "-T v142"

If it doesn't complain, leave it as it is. Perhaps this will yield a new build. If not, you may want to choose the updated OpenTelemetry build that is already checked in this repository. It may work for your use case.

In any case, plz keep me informed if the scripts provided a build for you.

**Comment by cnbleu** [comment]
Hi Moose! I have compiled it successfully with your new script after reinstall my windows and vs2022. But it still not work with vs2019. Anyway, I can build my own binary! You do a great job, thank you.
